// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    AppHeaderAdmin: typeof import('./src/components/AppHeader-admin.vue')['default']
    AppHeaderSoldier: typeof import('./src/components/AppHeader-soldier.vue')['default']
    HomePage: typeof import('./src/components/pages/HomePage.vue')['default']
    InputPoint: typeof import('./src/components/pages/InputPoint.vue')['default']
    InputVacation: typeof import('./src/components/pages/InputVacation.vue')['default']
    JoinInfo: typeof import('./src/components/pages/JoinInfo.vue')['default']
    JoinPage: typeof import('./src/components/pages/JoinPage.vue')['default']
    MyLogin: typeof import('./src/components/pages/MyLogin.vue')['default']
    PasswordReset: typeof import('./src/components/pages/PasswordReset.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/pages/Settings.vue')['default']
  }
}
